export const esperanto = {
  "2D": "[2Ð П]",
  "3D": "[3Ð П]",
  "A to Z": "[Å ţö Ž----- П國カ내]",
  "About": "[Åƀöûţ--- П國カ내]",
  "Access Dashboard": "[Åççéšš Ðåšĥƀöåŕð--------- П國カ내]",
  "Access Machine Control": "[Åççéšš Ṁåçĥîñé Çöñţŕöļ---------- П國カ내]",
  "Access Service Mode Page": "[Åççéšš Šéŕṽîçé Ṁöðé Þåĝé------------ П國カ내]",
  "Actions": "[Åçţîöñš------- П國カ내]",
  "Add New": "[Åðð Ñéŵ------- П國カ내]",
  "Add Widget": "[Åðð Ŵîðĝéţ------------- П國カ내]",
  "Additional Options": "[Åððîţîöñåļ Öþţîöñš----------- П國カ내]",
  "Administrator Permissions": "[Åðɱîñîšţŕåţöŕ Þéŕɱîššîöñš------------- П國カ내]",
  "Allow distribution of work across machine groups": "[Åļļöŵ ðîšţŕîƀûţîöñ öƒ ŵöŕķ åçŕöšš ɱåçĥîñé ĝŕöûþš--------------------- П國カ내]",
  "Allow non-optimal production": "[Åļļöŵ ñöñ-öþţîɱåļ þŕöðûçţîöñ--------------- П國カ내]",
  "Assigned to:": "[Åššîĝñéð ţö:----- П國カ내]",
  "Automatically Tab Between Fields With USB Scanner": "[Åûţöɱåţîçåļļý Ţåƀ Ɓéţŵééñ Ƒîéļðš Ŵîţĥ ÛŠƁ Šçåññéŕ---------------------- П國カ내]",
  "Available Machines": "[Åṽåîļåƀļé Ṁåçĥîñéš----------- П國カ내]",
};
