export const french = {
  "2D": "2D",
  "3D": "3D",
  "A to Z": "De A à Z",
  "About": "À propos",
  "Access Dashboard": "Accès au tableau de bord",
  "Access Machine Control": "Contrôle de la machine d&#39;accès",
  "Access Service Mode Page": "Accéder à la page du mode de service",
  "Actions": "Actions",
  "Add New": "Ajouter nouveau",
  "Add Widget": "Ajouter un widget",
  "Additional Options": "Options additionelles",
  "Administrator Permissions": "Autorisations d&#39;administrateur",
  "Allow non-optimal production": "Autoriser une production non optimale",
  "Allow distribution of work across machine groups": "Autoriser la distribution du travail entre les groupes de machines",
  "Assigned to:": "Assigné à:",
  "Automatically Tab Between Fields With USB Scanner": "Tabulation automatique entre les champs avec le scanner USB",
  "Available Machines": "Machines disponibles",
};
